### ISSUE TITLE
Invalid Details Or Account Not Confirmed

### ISSUE THREAD

**Issue by Thijsnuis** [ajayrandhawa/User-Management-PHP-MYSQL#12]
i have problems whit "Invalid Details Or Account Not Confirmed"

**Comment by mattmarich** [comment]
@Thijsnuis I'm still looking for root cause in my own instance but for some reason the md5 hash of the admin password had changed so I had to update the admin users pass manually in the db. Idk if you're having an issue with an admin user or standard account but I would suggest trying that.

**Comment by ectic2020** [comment]
Le mot de passe admin ne fonctionne pas, qui peut m'aider à résoudre le problème?

**Comment by mattmarich** [comment]
@ectic2020 Please try what I mentioned above. I only had the issue one time while I was using this project, in order to login with my admin account I had to manually enter correct md5 hash of my password for my user in the database.

**Comment by ajayrandhawa** [comment]
Thanks
