### ISSUE TITLE
images folder

### ISSUE THREAD

**Issue by meetmec12** [ajayrandhawa/User-Management-PHP-MYSQL#2]
Nice code. You omitted the images folder in the core code. This echo few error on sign up and rendered picture upload ineffective . Simply creating images folder solves the issue

**Comment by Ramius1701** [comment]
This corrects one of the signup issues 👍

**Comment by seanlacoursiere** [comment]
Hi so where did you create the folder? Did you simply create an image folder on the root?

**Comment by pebwindkraft** [comment]
just added the images folder in the root of the UserMgmt folder (parallel to admin, css, js or vendor). Registering a user works, and the avatar file can be seen in the images directory.

**Comment by ajayrandhawa** [comment]
Create Images folder in root, solve signup problem
