### ISSUE TITLE
wonder why u bother using a header file

### ISSUE THREAD

**Issue by LebToki** [ajayrandhawa/User-Management-PHP-MYSQL#21]
when every single page you have a header of its own
while you can use child sections and various includes to keep your code streamlined and well documented

**Comment by abhasdudeja** [comment]
I did think the same.
This not only helps in stream-lining the code but also allows easier edit to the header (if needed) in a single go.

**Comment by ajayrandhawa** [comment]
Thanks for your info, this basic project way back no longer working on it
