### ISSUE TITLE
signup fails

### ISSUE THREAD

**Issue by Ramius1701** [ajayrandhawa/User-Management-PHP-MYSQL#3]
When attempting to create a new account via the signup link it fails to create the user in the mysql database. The Admin gets the message via notification

**Comment by MuhammadHamdan7** [comment]
the problem in the status column at users table you have tow way to fix this :D 
1) mark status column as null-able so you will be able to add users without a status value 
2) add the status to the insert query with value (1) to make user as confirmed
and that is it :)

**Comment by kevinmundia6771** [comment]
How do i  confirm a sure from the amin side.

**Comment by kevinmundia6771** [comment]
How do i  confirm a user 👤 from the admin side

**Comment by kevinmundia6771** [comment]
Plizz help out people.

**Comment by kenth23** [comment]
how to confirm user ??

**Comment by ajayrandhawa** [comment]
Create a "images" folder in the root folder, solve signup problem
