### ISSUE TITLE
No Date and time for the registartion

### ISSUE THREAD

**Issue by skyefaceconcept** [ajayrandhawa/User-Management-PHP-MYSQL#4]
No Date and time for the registartion

**Comment by meetmec12** [comment]
You can simply add this by updating your database structure. In phpmyadmin , under new rows Date and time
Now in register.php edit the code to include date () ..Also edit the form action to insert your new fields .

**Comment by noumank007** [comment]
Or you can simply just add the field of datetime in database table and set its datetype to datetime and default value to CURRENT_TIMESTAMP. So whenever new data comes it will get the current time of data insertion and add it to database. :)
