### ISSUE TITLE
Error: SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by ummaruje** [ajayrandhawa/User-Management-PHP-MYSQL#5]
After starting my Mamp server, i created new database and imported the database.sql file successfully and i put the work on htdots folder. when running on chrome browser , it gives me this error "Error: SQLSTATE[HY000] [2002] Connection refused"

**Comment by Lovemakery** [comment]
How did you solve that problem?

**Comment by crazzyguti** [comment]
change
includes/config.php
and  
admin/includes/config.php
work for me

**Comment by Lovemakery** [comment]
How did you set it up?
