### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by frozzen91** [ajayrandhawa/User-Management-PHP-MYSQL#8]
Hi, i have one request for you.. it's possible add other authorization? and the pozzibility for change autorizzation in the pannel admin?now we have admin and general user, can you insert other user and cookie? thank you for help me

**Comment by ajayrandhawa** [comment]
Yes can Change

**Comment by frozzen91** [comment]
can you edit the files?  I'm not able to do ..

**Comment by ajayrandhawa** [comment]
Sorry, Currently Busy
